// <auto-generated />
using System;
using ClothingStore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingStore.Persistence.Migrations
{
    [DbContext(typeof(ClothingStoreDbContext))]
    [Migration("20230326130653_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingStore.Domain.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BrandId");

                    b.HasIndex("BrandId")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Adidas",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6306),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6315)
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Puma",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6317),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6317)
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Nike",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6318),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6319)
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Diadora",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6319),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6320)
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "The North Face",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6320),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6321)
                        },
                        new
                        {
                            BrandId = 6,
                            BrandName = "Fred Perry",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6322),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6323)
                        },
                        new
                        {
                            BrandId = 7,
                            BrandName = "Asics",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6323),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6324)
                        },
                        new
                        {
                            BrandId = 8,
                            BrandName = "Vans",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6324),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6324)
                        },
                        new
                        {
                            BrandId = 9,
                            BrandName = "Reebook",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6325),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6325)
                        },
                        new
                        {
                            BrandId = 10,
                            BrandName = "Converse",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6327),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6327)
                        },
                        new
                        {
                            BrandId = 11,
                            BrandName = "ТВОЕ",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6327),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6328)
                        },
                        new
                        {
                            BrandId = 12,
                            BrandName = "Mark Formelle",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6328),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6329)
                        });
                });

            modelBuilder.Entity("ClothingStore.Domain.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"));

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ColorId");

                    b.HasIndex("ColorId")
                        .IsUnique();

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            ColorName = "Белый",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6388),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6389)
                        },
                        new
                        {
                            ColorId = 2,
                            ColorName = "Черный",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6408),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6409)
                        },
                        new
                        {
                            ColorId = 3,
                            ColorName = "Желтый",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6409),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6409)
                        },
                        new
                        {
                            ColorId = 4,
                            ColorName = "Коричневый",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6410),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6410)
                        },
                        new
                        {
                            ColorId = 5,
                            ColorName = "Розовый",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6414),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6414)
                        },
                        new
                        {
                            ColorId = 6,
                            ColorName = "Бежевый",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6416),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6416)
                        },
                        new
                        {
                            ColorId = 7,
                            ColorName = "Серый",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6417),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6417)
                        },
                        new
                        {
                            ColorId = 8,
                            ColorName = "Зеленый",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6417),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6418)
                        },
                        new
                        {
                            ColorId = 9,
                            ColorName = "Синий",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6418),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6419)
                        },
                        new
                        {
                            ColorId = 10,
                            ColorName = "Фиолетовый",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6420),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6420)
                        },
                        new
                        {
                            ColorId = 11,
                            ColorName = "Красный",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6421),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6421)
                        },
                        new
                        {
                            ColorId = 12,
                            ColorName = "Оранжевый",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6421),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6422)
                        });
                });

            modelBuilder.Entity("ClothingStore.Domain.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GenderId");

                    b.HasIndex("GenderId")
                        .IsUnique();

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6472),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderName = "Male",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6473)
                        },
                        new
                        {
                            GenderId = 2,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6476),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderName = "Female",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6476)
                        });
                });

            modelBuilder.Entity("ClothingStore.Domain.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            City = "Витебск",
                            Country = "Беларусь",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6566),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = "210021",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6566)
                        },
                        new
                        {
                            LocationId = 2,
                            City = "Москва",
                            Country = "Россия",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6571),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = "210021",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6571)
                        },
                        new
                        {
                            LocationId = 3,
                            City = "Киев",
                            Country = "Украина",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6572),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = "210021",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6572)
                        },
                        new
                        {
                            LocationId = 4,
                            City = "Могилев",
                            Country = "Беларусь",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6573),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = "210021",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6573)
                        },
                        new
                        {
                            LocationId = 5,
                            City = "Минск",
                            Country = "Беларусь",
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6574),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Index = "210021",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6575)
                        });
                });

            modelBuilder.Entity("ClothingStore.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.HasIndex("GenderId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BrandId = 10,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6750),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Практичная и прочная обувь.",
                            GenderId = 1,
                            Image = "https://avatars.mds.yandex.net/get-mpic/7543961/img_id2876985684977519291.jpeg/orig",
                            Price = 80m,
                            ProductName = "Кеды Converse",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6751),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 2,
                            BrandId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6753),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Основная часть кроссовок изготовлена из устойчивых к износу материалов.",
                            GenderId = 2,
                            Image = "https://basket-10.wb.ru/vol1492/part149253/149253341/images/big/3.jpg",
                            Price = 175m,
                            ProductName = "Кроссовки Adidas",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6753),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 3,
                            BrandId = 6,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6754),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Изделие из фактурного хлопкового трикотажа украшено вышивкой с принтом на груди",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLABL206701_17128948_1_v1_2x.jpg",
                            Price = 289m,
                            ProductName = "Футболка Fred Perry",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6755),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 4,
                            BrandId = 7,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6755),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кроссовки выполнены из сетчатого текстиля, растягивается при естественном движении стопы и создает удобную посадку. ",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLACH890601_19173162_1_v1.jpg",
                            Price = 486m,
                            ProductName = "Кроссовки Asics",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 5,
                            BrandId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6756),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Основная часть кроссовок изготовлена из устойчивых к износу материалов.",
                            GenderId = 2,
                            Image = "https://basket-10.wb.ru/vol1492/part149253/149253341/images/big/3.jpg",
                            Price = 175m,
                            ProductName = "Кроссовки Adidas",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6757),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 6,
                            BrandId = 6,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6758),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Изделие из фактурного хлопкового трикотажа украшено вышивкой с принтом на груди",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLABL206701_17128948_1_v1_2x.jpg",
                            Price = 289m,
                            ProductName = "Футболка Fred Perry",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6758),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 7,
                            BrandId = 7,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6759),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кроссовки выполнены из сетчатого текстиля, растягивается при естественном движении стопы и создает удобную посадку. ",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLACH890601_19173162_1_v1.jpg",
                            Price = 486m,
                            ProductName = "Кроссовки Asics",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6760),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 8,
                            BrandId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6778),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Основная часть кроссовок изготовлена из устойчивых к износу материалов.",
                            GenderId = 2,
                            Image = "https://basket-10.wb.ru/vol1492/part149253/149253341/images/big/3.jpg",
                            Price = 175m,
                            ProductName = "Кроссовки Adidas",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6779),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 9,
                            BrandId = 6,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6780),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Изделие из фактурного хлопкового трикотажа украшено вышивкой с принтом на груди",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLABL206701_17128948_1_v1_2x.jpg",
                            Price = 289m,
                            ProductName = "Футболка Fred Perry",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6780),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 10,
                            BrandId = 7,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6782),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кроссовки выполнены из сетчатого текстиля, растягивается при естественном движении стопы и создает удобную посадку. ",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLACH890601_19173162_1_v1.jpg",
                            Price = 486m,
                            ProductName = "Кроссовки Asics",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6782),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 11,
                            BrandId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6783),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Основная часть кроссовок изготовлена из устойчивых к износу материалов.",
                            GenderId = 2,
                            Image = "https://basket-10.wb.ru/vol1492/part149253/149253341/images/big/3.jpg",
                            Price = 175m,
                            ProductName = "Кроссовки Adidas",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6783),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 12,
                            BrandId = 6,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6784),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Изделие из фактурного хлопкового трикотажа украшено вышивкой с принтом на груди",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLABL206701_17128948_1_v1_2x.jpg",
                            Price = 289m,
                            ProductName = "Футболка Fred Perry",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6784),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 13,
                            BrandId = 7,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6785),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кроссовки выполнены из сетчатого текстиля, растягивается при естественном движении стопы и создает удобную посадку. ",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLACH890601_19173162_1_v1.jpg",
                            Price = 486m,
                            ProductName = "Кроссовки Asics",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6786),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 14,
                            BrandId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6786),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Основная часть кроссовок изготовлена из устойчивых к износу материалов.",
                            GenderId = 2,
                            Image = "https://basket-10.wb.ru/vol1492/part149253/149253341/images/big/3.jpg",
                            Price = 175m,
                            ProductName = "Кроссовки Adidas",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6787),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 15,
                            BrandId = 6,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6788),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Изделие из фактурного хлопкового трикотажа украшено вышивкой с принтом на груди",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLABL206701_17128948_1_v1_2x.jpg",
                            Price = 289m,
                            ProductName = "Футболка Fred Perry",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6788),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 16,
                            BrandId = 7,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6789),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кроссовки выполнены из сетчатого текстиля, растягивается при естественном движении стопы и создает удобную посадку. ",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLACH890601_19173162_1_v1.jpg",
                            Price = 486m,
                            ProductName = "Кроссовки Asics",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6789),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 17,
                            BrandId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6790),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Основная часть кроссовок изготовлена из устойчивых к износу материалов.",
                            GenderId = 2,
                            Image = "https://basket-10.wb.ru/vol1492/part149253/149253341/images/big/3.jpg",
                            Price = 175m,
                            ProductName = "Кроссовки Adidas",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6790),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 18,
                            BrandId = 6,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6793),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Изделие из фактурного хлопкового трикотажа украшено вышивкой с принтом на груди",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLABL206701_17128948_1_v1_2x.jpg",
                            Price = 289m,
                            ProductName = "Футболка Fred Perry",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6794),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 19,
                            BrandId = 7,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6796),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кроссовки выполнены из сетчатого текстиля, растягивается при естественном движении стопы и создает удобную посадку. ",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLACH890601_19173162_1_v1.jpg",
                            Price = 486m,
                            ProductName = "Кроссовки Asics",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6796),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 20,
                            BrandId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6797),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Основная часть кроссовок изготовлена из устойчивых к износу материалов.",
                            GenderId = 2,
                            Image = "https://basket-10.wb.ru/vol1492/part149253/149253341/images/big/3.jpg",
                            Price = 175m,
                            ProductName = "Кроссовки Adidas",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6797),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 21,
                            BrandId = 6,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6798),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Изделие из фактурного хлопкового трикотажа украшено вышивкой с принтом на груди",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLABL206701_17128948_1_v1_2x.jpg",
                            Price = 289m,
                            ProductName = "Футболка Fred Perry",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6799),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 22,
                            BrandId = 7,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6799),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кроссовки выполнены из сетчатого текстиля, растягивается при естественном движении стопы и создает удобную посадку. ",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLACH890601_19173162_1_v1.jpg",
                            Price = 486m,
                            ProductName = "Кроссовки Asics",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6800),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 23,
                            BrandId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6801),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Основная часть кроссовок изготовлена из устойчивых к износу материалов.",
                            GenderId = 2,
                            Image = "https://basket-10.wb.ru/vol1492/part149253/149253341/images/big/3.jpg",
                            Price = 175m,
                            ProductName = "Кроссовки Adidas",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6801),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 24,
                            BrandId = 6,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6802),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Изделие из фактурного хлопкового трикотажа украшено вышивкой с принтом на груди",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLABL206701_17128948_1_v1_2x.jpg",
                            Price = 289m,
                            ProductName = "Футболка Fred Perry",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6802),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 25,
                            BrandId = 7,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6803),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кроссовки выполнены из сетчатого текстиля, растягивается при естественном движении стопы и создает удобную посадку. ",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLACH890601_19173162_1_v1.jpg",
                            Price = 486m,
                            ProductName = "Кроссовки Asics",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6806),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 26,
                            BrandId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6807),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Основная часть кроссовок изготовлена из устойчивых к износу материалов.",
                            GenderId = 2,
                            Image = "https://basket-10.wb.ru/vol1492/part149253/149253341/images/big/3.jpg",
                            Price = 175m,
                            ProductName = "Кроссовки Adidas",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6807),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 27,
                            BrandId = 6,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6808),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Изделие из фактурного хлопкового трикотажа украшено вышивкой с принтом на груди",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLABL206701_17128948_1_v1_2x.jpg",
                            Price = 289m,
                            ProductName = "Футболка Fred Perry",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6808),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 28,
                            BrandId = 7,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6809),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кроссовки выполнены из сетчатого текстиля, растягивается при естественном движении стопы и создает удобную посадку. ",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLACH890601_19173162_1_v1.jpg",
                            Price = 486m,
                            ProductName = "Кроссовки Asics",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6809),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 29,
                            BrandId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6810),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Основная часть кроссовок изготовлена из устойчивых к износу материалов.",
                            GenderId = 2,
                            Image = "https://basket-10.wb.ru/vol1492/part149253/149253341/images/big/3.jpg",
                            Price = 175m,
                            ProductName = "Кроссовки Adidas",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6811),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 30,
                            BrandId = 6,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6812),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Изделие из фактурного хлопкового трикотажа украшено вышивкой с принтом на груди",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLABL206701_17128948_1_v1_2x.jpg",
                            Price = 289m,
                            ProductName = "Футболка Fred Perry",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6812),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 31,
                            BrandId = 7,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6813),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кроссовки выполнены из сетчатого текстиля, растягивается при естественном движении стопы и создает удобную посадку. ",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLACH890601_19173162_1_v1.jpg",
                            Price = 486m,
                            ProductName = "Кроссовки Asics",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6813),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 32,
                            BrandId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6814),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Основная часть кроссовок изготовлена из устойчивых к износу материалов.",
                            GenderId = 2,
                            Image = "https://basket-10.wb.ru/vol1492/part149253/149253341/images/big/3.jpg",
                            Price = 175m,
                            ProductName = "Кроссовки Adidas",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6814),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 33,
                            BrandId = 6,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6815),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Изделие из фактурного хлопкового трикотажа украшено вышивкой с принтом на груди",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLABL206701_17128948_1_v1_2x.jpg",
                            Price = 289m,
                            ProductName = "Футболка Fred Perry",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6815),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        },
                        new
                        {
                            ProductId = 34,
                            BrandId = 7,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6817),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кроссовки выполнены из сетчатого текстиля, растягивается при естественном движении стопы и создает удобную посадку. ",
                            GenderId = 1,
                            Image = "https://a.lmcdn.ru/product/R/T/RTLACH890601_19173162_1_v1.jpg",
                            Price = 486m,
                            ProductName = "Кроссовки Asics",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6818),
                            UserId = "3046bb27-a9f9-4cfb-87ee-0853cae48701"
                        });
                });

            modelBuilder.Entity("ClothingStore.Domain.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SeasonId");

                    b.HasIndex("SeasonId")
                        .IsUnique();

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            SeasonId = 1,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6521),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonName = "Демисезон",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6521)
                        },
                        new
                        {
                            SeasonId = 2,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6523),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonName = "Весна",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6524)
                        },
                        new
                        {
                            SeasonId = 3,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6524),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonName = "Зима",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6524)
                        },
                        new
                        {
                            SeasonId = 4,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6525),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonName = "Осень",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6525)
                        },
                        new
                        {
                            SeasonId = 5,
                            CreatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6526),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonName = "Лето",
                            UpdatedDate = new DateTime(2023, 3, 26, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6526)
                        });
                });

            modelBuilder.Entity("ClothingStore.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3046bb27-a9f9-4cfb-87ee-0853cae48701",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b84f97b2-007f-4781-9ee7-9dcedd5185d3",
                            EmailConfirmed = false,
                            LocationId = 1,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEP9tfDrMeXhTcSNOK4ZvChJUmRJItt9sErtW/Kv2+5qH1cWaXHwHQAstiixTLIBh8g==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "7iK7mWYVQgEriP+Zoia/UfiMKon/4cqUijRncBrplJpt1C0CJDZkstZsXTtnF4SMsv9Wfv+HU2fErMvHjTPW4g==",
                            RefreshTokenExpiryTime = new DateTime(2023, 3, 27, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6672),
                            SecurityStamp = "DKOIJFTBZLFCJCNGXCZ3AZRQ4BZ2K5SA",
                            TwoFactorEnabled = false,
                            UserName = "mkr.e"
                        },
                        new
                        {
                            Id = "3046bb27-a9f9-4cfb-87ee-0853cae48702",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b84f97b2-007f-4781-9ee7-9dcedd5185d3",
                            EmailConfirmed = false,
                            LocationId = 2,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEP9tfDrMeXhTcSNOK4ZvChJUmRJItt9sErtW/Kv2+5qH1cWaXHwHQAstiixTLIBh8g==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "7iK7mWYVQgEriP+Zoia/UfiMKon/4cqUijRncBrplJpt1C0CJDZkstZsXTtnF4SMsv9Wfv+HU2fErMvHjTPW4g==",
                            RefreshTokenExpiryTime = new DateTime(2023, 3, 27, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6681),
                            SecurityStamp = "DKOIJFTBZLFCJCNGXCZ3AZRQ4BZ2K5SA",
                            TwoFactorEnabled = false,
                            UserName = "Andrey"
                        },
                        new
                        {
                            Id = "3046bb27-a9f9-4cfb-87ee-0853cae48703",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b84f97b2-007f-4781-9ee7-9dcedd5185d3",
                            EmailConfirmed = false,
                            LocationId = 3,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEP9tfDrMeXhTcSNOK4ZvChJUmRJItt9sErtW/Kv2+5qH1cWaXHwHQAstiixTLIBh8g==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "7iK7mWYVQgEriP+Zoia/UfiMKon/4cqUijRncBrplJpt1C0CJDZkstZsXTtnF4SMsv9Wfv+HU2fErMvHjTPW4g==",
                            RefreshTokenExpiryTime = new DateTime(2023, 3, 27, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6687),
                            SecurityStamp = "DKOIJFTBZLFCJCNGXCZ3AZRQ4BZ2K5SA",
                            TwoFactorEnabled = false,
                            UserName = "Vitali"
                        },
                        new
                        {
                            Id = "3046bb27-a9f9-4cfb-87ee-0853cae48704",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b84f97b2-007f-4781-9ee7-9dcedd5185d3",
                            EmailConfirmed = false,
                            LocationId = 4,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEP9tfDrMeXhTcSNOK4ZvChJUmRJItt9sErtW/Kv2+5qH1cWaXHwHQAstiixTLIBh8g==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "7iK7mWYVQgEriP+Zoia/UfiMKon/4cqUijRncBrplJpt1C0CJDZkstZsXTtnF4SMsv9Wfv+HU2fErMvHjTPW4g==",
                            RefreshTokenExpiryTime = new DateTime(2023, 3, 27, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6694),
                            SecurityStamp = "DKOIJFTBZLFCJCNGXCZ3AZRQ4BZ2K5SA",
                            TwoFactorEnabled = false,
                            UserName = "Alexandr"
                        },
                        new
                        {
                            Id = "3046bb27-a9f9-4cfb-87ee-0853cae48705",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b84f97b2-007f-4781-9ee7-9dcedd5185d3",
                            EmailConfirmed = false,
                            LocationId = 5,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEP9tfDrMeXhTcSNOK4ZvChJUmRJItt9sErtW/Kv2+5qH1cWaXHwHQAstiixTLIBh8g==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "7iK7mWYVQgEriP+Zoia/UfiMKon/4cqUijRncBrplJpt1C0CJDZkstZsXTtnF4SMsv9Wfv+HU2fErMvHjTPW4g==",
                            RefreshTokenExpiryTime = new DateTime(2023, 3, 27, 16, 6, 53, 301, DateTimeKind.Local).AddTicks(6700),
                            SecurityStamp = "DKOIJFTBZLFCJCNGXCZ3AZRQ4BZ2K5SA",
                            TwoFactorEnabled = false,
                            UserName = "Vasilisa"
                        });
                });

            modelBuilder.Entity("ColorProduct", b =>
                {
                    b.Property<int>("ColorsColorId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.HasKey("ColorsColorId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("ColorProduct");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductSeason", b =>
                {
                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonsSeasonId")
                        .HasColumnType("int");

                    b.HasKey("ProductsProductId", "SeasonsSeasonId");

                    b.HasIndex("SeasonsSeasonId");

                    b.ToTable("ProductSeason");
                });

            modelBuilder.Entity("ClothingStore.Domain.Product", b =>
                {
                    b.HasOne("ClothingStore.Domain.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Domain.Gender", "Gender")
                        .WithMany("Products")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Domain.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Gender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClothingStore.Domain.User", b =>
                {
                    b.HasOne("ClothingStore.Domain.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ColorProduct", b =>
                {
                    b.HasOne("ClothingStore.Domain.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorsColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClothingStore.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClothingStore.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClothingStore.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductSeason", b =>
                {
                    b.HasOne("ClothingStore.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Domain.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonsSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClothingStore.Domain.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ClothingStore.Domain.Gender", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ClothingStore.Domain.Location", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ClothingStore.Domain.User", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
